Inhibit a warning message on pipefail
sys.exit() throws an exception on pipefail. In this case, opy gave a
warning message and finished with the exit status 120. Since I want to
make opy ignore PIPEFAIL, I have replaced sys.exit() to os._exit().

```
$ yes aho | opy '[F1]' | head
aho
aho
aho
aho
aho
aho
aho
aho
aho
aho
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
$ echo ${PIPESTATUS[@]}
141 120 0
$ yes aho | opy '[F1]' | head
aho
aho
aho
aho
aho
aho
aho
aho
aho
aho
$ echo ${PIPESTATUS[@]}
141 0 0
```